-- V1: Panchayat-centered farmer application database.
--
-- APPLICATION DATABASE tables (operational data). This is NOT ML training
-- data: the Python pipeline under data/, models/ and notebooks/ is untouched
-- and must stay untouched.
--
-- The previous runtime database was ephemeral in-memory H2 (no persisted
-- data to preserve), so a fresh PostgreSQL database receives the full
-- schema from this migration, including the pre-existing `feedback` table
-- recreated compatibly with model/Feedback.java (IDENTITY id, same columns).
-- The Feedback API behaviour is unchanged.
--
-- Naming: PKs pk_<table>, FKs fk_<child>_<parent>, uniques uq_*, checks
-- chk_*, indexes idx_*. SQL is kept to standard constructs shared by
-- PostgreSQL and H2 so the migration-alignment test can run it on H2.

-- ---------------------------------------------------------------- feedback
CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advisory_helpful BOOLEAN,
    block VARCHAR(255),
    comments VARCHAR(255),
    crop_stage VARCHAR(255),
    farmer_name VARCHAR(255),
    submitted_at TIMESTAMP(6)
);

-- ---------------------------------------------------------------- panchayat
CREATE TABLE panchayat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    block_name VARCHAR(80) NOT NULL,
    district_name VARCHAR(80) NOT NULL DEFAULT 'Sangrur',
    state_name VARCHAR(80) NOT NULL DEFAULT 'Punjab',
    bhuvan_block_id VARCHAR(32),
    state_code VARCHAR(16),
    district_code VARCHAR(16),
    block_code VARCHAR(16),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_panchayat_block_name UNIQUE (block_name, name)
);
-- NOTE: no UNIQUE(name): e.g. Ubhawal exists in Sangrur AND Sunam blocks.

-- ------------------------------------------------------- panchayat_official
CREATE TABLE panchayat_official (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    username VARCHAR(80) NOT NULL,
    role VARCHAR(40) NOT NULL DEFAULT 'PANCHAYAT_OFFICIAL',
    panchayat_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_official_username UNIQUE (username),
    CONSTRAINT fk_official_panchayat FOREIGN KEY (panchayat_id)
        REFERENCES panchayat (id) ON DELETE RESTRICT
);
-- No password column in this phase (future authentication phase).

-- -------------------------------------------------------------------- farmer
CREATE TABLE farmer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_code VARCHAR(32) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    phone VARCHAR(20),
    village VARCHAR(120),
    panchayat_id BIGINT NOT NULL,
    registered_by_official_id BIGINT,
    notes VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_farmer_code UNIQUE (farmer_code),
    CONSTRAINT fk_farmer_panchayat FOREIGN KEY (panchayat_id)
        REFERENCES panchayat (id) ON DELETE RESTRICT,
    CONSTRAINT fk_farmer_registrar FOREIGN KEY (registered_by_official_id)
        REFERENCES panchayat_official (id) ON DELETE SET NULL
);

-- ---------------------------------------------------------------------- farm
CREATE TABLE farm (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id BIGINT NOT NULL,
    plot_label VARCHAR(80),
    area_acres DOUBLE PRECISION,
    village VARCHAR(120),
    block_name VARCHAR(80) NOT NULL,
    panchayat_name VARCHAR(120),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_method VARCHAR(40),
    soil_texture VARCHAR(60),
    irrigation_source VARCHAR(60),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_farm_farmer FOREIGN KEY (farmer_id)
        REFERENCES farmer (id) ON DELETE CASCADE,
    CONSTRAINT chk_farm_area CHECK (area_acres IS NULL OR area_acres > 0),
    CONSTRAINT chk_farm_lat CHECK (latitude IS NULL OR (latitude >= -90 AND latitude <= 90)),
    CONSTRAINT chk_farm_lon CHECK (longitude IS NULL OR (longitude >= -180 AND longitude <= 180)),
    CONSTRAINT chk_farm_latlon_pair CHECK (
        (latitude IS NULL AND longitude IS NULL)
        OR (latitude IS NOT NULL AND longitude IS NOT NULL)),
    CONSTRAINT chk_farm_location_method CHECK (location_method IS NULL OR location_method IN (
        'PANCHAYAT_DEFAULT', 'BLOCK_CENTROID', 'MAP_PICKED', 'GPS_CAPTURE'))
);
-- No PostGIS: coordinates are optional official-derived points only.

-- ------------------------------------------------------------- crop_planting
CREATE TABLE crop_planting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT NOT NULL,
    crop_name VARCHAR(120) NOT NULL,
    variety VARCHAR(120),
    season VARCHAR(16) NOT NULL,
    crop_year INTEGER NOT NULL,
    sowing_date DATE,
    harvest_date DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_crop_farm FOREIGN KEY (farm_id)
        REFERENCES farm (id) ON DELETE CASCADE,
    CONSTRAINT uq_crop_farm_season_year_name UNIQUE (farm_id, season, crop_year, crop_name),
    CONSTRAINT chk_crop_season CHECK (season IN ('KHARIF', 'RABI', 'ZAID')),
    CONSTRAINT chk_crop_year CHECK (crop_year BETWEEN 2000 AND 2100),
    CONSTRAINT chk_crop_dates CHECK (
        harvest_date IS NULL OR sowing_date IS NULL OR harvest_date >= sowing_date)
);
-- Append-only history: no is_current flag; "current" = latest by
-- (crop_year, created_at) per farm via repository query.

-- ------------------------------------------------------------------- indexes
CREATE INDEX idx_official_panchayat ON panchayat_official (panchayat_id);
CREATE INDEX idx_farmer_panchayat ON farmer (panchayat_id);
CREATE INDEX idx_farmer_panchayat_name ON farmer (panchayat_id, full_name);
CREATE INDEX idx_farmer_registrar ON farmer (registered_by_official_id);
CREATE INDEX idx_farm_farmer ON farm (farmer_id);
CREATE INDEX idx_crop_farm ON crop_planting (farm_id);
CREATE INDEX idx_crop_farm_year_season ON crop_planting (farm_id, crop_year, season);
